### ISSUE TITLE
postgres launch fails

### ISSUE THREAD

**Issue by NyanRaven** [drnoa/kivitendo_docker#2]
I installed latest version docker version on EC2 and pulled the docker from repo. But I'm getting the following error  INFO gave up: postgres entered FATAL state, too many start retries too quickly.
I also tried it on Docker for Mac with the same issue. Is there something else I have to configure?

**Comment by drnoa** [comment]
I am sorry there was a change in the default docker container. I fixed it.
Please try again with the latest dockerfile or docker pull drnoa/kivitendo-docker
