### ISSUE TITLE
404 error on clean new install

### ISSUE THREAD

**Issue by rschaerer** [drnoa/kivitendo_docker#5]
When I start a clean new install from commit 02873e8f864bda0e3f6cb3771bb352fb7ded8627 the webserver delivers the index.html and forwards to `/controller.pl?action=LoginScreen/user_login`, but there an 404 error is displayed.

The apache `error.log` shows:

````
script not found or unable to stat: /var/www/kivitendo-erp/controller.pl
````

Anyone with the same issues and what can I do?

**Comment by drnoa** [comment]
I could reproduce the error and I am trying to fix it as soon as possible.

[Sun Dec 22 19:41:39.809472 2019] [cgi:error] [pid 22] [client 172.17.0.1:41728] AH02811: script not found or unable to stat: /var/www/kivitendo-erp/controller.pl

**Comment by drnoa** [comment]
I was able to fix the problem. I upgrade the project to fastCGI and i integrated Kivitendo CRM as well. Give it a try and let me know if you see any problems
