### ISSUE TITLE
Why do you work with 2 different postgresql package repos?

### ISSUE THREAD

**Issue by groovyman** [drnoa/kivitendo_docker#7]
Salut 
i am trying to run your docker-project but i am running into some problems.
It looks like, that the installation gets messed up with the standard debian/ubuntu 
package architectur of debian and the loaded one from apt.postgresql.org.

What was your intention to inject an old 9.5 postgres into a 10 version, that is provided by ubuntu?

Thank you
Christian

**Comment by drnoa** [comment]
Hi groovyman

You are right. I added the repository in the times 9.5 was not yet the stable postgres package in ubuntu LTS. 
Now i changed to postgres 10 and i will try if it even works with v11 or higher.
